[files]
extend-exclude = ["build/", "build-*/", "*.svg", "data/emoji/emoji.json", "data/dictionaries/", "tests/typing/"]

[default.extend-words]
INVOKABLE = "INVOKABLE"
asai = "asai"
calculat = "calculat"
conver = "conver"
targetted = "targetted"
ba = "ba"
fo = "fo"
