[files]
extend-exclude = ["build/", "build-*/", "*.svg", "data/emoji/emoji.json"]

[default.extend-words]
INVOKABLE = "INVOKABLE"
asai = "asai"
calculat = "calculat"
conver = "conver"
targetted = "targetted"
